name: iOS CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-15

    steps:
        - uses: actions/checkout@v4

        - name: Select Xcode 16
          run: sudo xcode-select -switch /Applications/Xcode_16.app

        - name: Build
          run: xcodebuild clean build -project clothes_shop.xcodeproj -scheme clothes_shop -destination 'id=B59C6C56-3086-4088-BB51-98A98B7518ED'

        - name: Run tests
          run: xcodebuild test -project clothes_shop.xcodeproj -scheme clothes_shop -destination 'id=B59C6C56-3086-4088-BB51-98A98B7518ED'
